import sys
import re
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parents[1] / "src"))

from fundos.storage.database import SCHEMA  # noqa: E402
from fundos.storage import Database  # noqa: E402
from fundos.storage.postgres_migrations import (  # noqa: E402
    POSTGRES_BASELINE_VERSION,
    apply_postgres_migrations,
    postgres_migrations,
    split_sql_statements,
    sqlite_schema_to_postgres,
)


class Result:
    def __init__(self, rows=()):
        self.rows = rows

    def fetchall(self):
        return self.rows


class MigrationConnection:
    def __init__(self):
        self.records = {}
        self.calls = []

    def execute(self, query, parameters=()):
        self.calls.append((query, parameters))
        normalized = " ".join(query.split()).lower()
        if normalized.startswith("select version, name, checksum from schema_migrations"):
            return Result([
                {
                    "version": version,
                    "name": self.records[version]["name"],
                    "checksum": self.records[version]["checksum"],
                }
                for version in sorted(self.records)
            ])
        if normalized.startswith("insert into schema_migrations"):
            self.records[parameters[0]] = {
                "name": parameters[1],
                "checksum": parameters[2],
            }
        if normalized.startswith("update schema_migrations set checksum"):
            self.records[parameters[1]]["checksum"] = parameters[0]
        if normalized.startswith("delete from schema_migrations"):
            del self.records[parameters[0]]
        return Result()


class PostgresMigrationTests(unittest.TestCase):
    def test_converts_current_schema_to_postgres_ddl(self) -> None:
        converted = sqlite_schema_to_postgres(SCHEMA)

        self.assertNotIn("PRAGMA", converted)
        self.assertNotIn("AUTOINCREMENT", converted)
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", converted)
        self.assertNotIn(" REAL ", converted)
        self.assertIn("DOUBLE PRECISION", converted)
        self.assertIn("CREATE TABLE IF NOT EXISTS benchmark_nav", converted)

    def test_builds_baseline_and_reversible_version_15(self) -> None:
        migrations = postgres_migrations(SCHEMA)

        self.assertEqual(len(migrations), 2)
        self.assertEqual(migrations[0].version, POSTGRES_BASELINE_VERSION)
        self.assertGreater(len(migrations[0].statements), 30)
        self.assertTrue(all(";" not in statement for statement in migrations[0].statements))
        self.assertNotIn("idx_raw_evidence_review_published", "\n".join(migrations[0].statements))
        self.assertEqual(migrations[1].version, 15)
        self.assertTrue(migrations[1].reversible)
        self.assertEqual(len(migrations[1].checksum), 64)

    def test_postgres_baseline_contains_every_sqlite_business_table(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            database = Database(Path(directory) / "inventory.sqlite3")
            database.initialize()
            sqlite_tables = set(database.list_tables())
        baseline_sql = "\n".join(postgres_migrations(SCHEMA)[0].statements)
        postgres_tables = set(re.findall(
            r"CREATE TABLE IF NOT EXISTS\s+([A-Za-z_][A-Za-z0-9_]*)",
            baseline_sql,
            flags=re.IGNORECASE,
        ))

        self.assertEqual(postgres_tables, sqlite_tables)

    def test_applies_baseline_idempotently(self) -> None:
        connection = MigrationConnection()

        first = apply_postgres_migrations(connection, SCHEMA)
        calls_after_first = len(connection.calls)
        second = apply_postgres_migrations(connection, SCHEMA)

        self.assertEqual(first, 15)
        self.assertEqual(second, 15)
        self.assertEqual(set(connection.records), {POSTGRES_BASELINE_VERSION, 15})
        second_run_calls = connection.calls[calls_after_first:]
        self.assertEqual(len(second_run_calls), 3)

    def test_rolls_version_15_back_and_can_reapply_it(self) -> None:
        connection = MigrationConnection()
        apply_postgres_migrations(connection, SCHEMA)

        rolled_back = apply_postgres_migrations(
            connection,
            SCHEMA,
            target_version=14,
        )
        upgraded = apply_postgres_migrations(connection, SCHEMA)

        self.assertEqual(rolled_back, 14)
        self.assertEqual(upgraded, 15)
        self.assertIn(15, connection.records)
        self.assertTrue(any(
            "drop index if exists idx_raw_evidence_review_published" in
            " ".join(query.split()).lower()
            for query, _ in connection.calls
        ))

    def test_rejects_changed_applied_migration(self) -> None:
        connection = MigrationConnection()
        apply_postgres_migrations(connection, SCHEMA)
        connection.records[15]["checksum"] = "tampered"

        with self.assertRaisesRegex(ValueError, "checksum mismatch"):
            apply_postgres_migrations(connection, SCHEMA)

    def test_adopts_checksum_for_existing_baseline_ledger(self) -> None:
        connection = MigrationConnection()
        connection.records[14] = {
            "name": "baseline_current_schema",
            "checksum": None,
        }

        applied = apply_postgres_migrations(
            connection,
            SCHEMA,
            target_version=14,
        )

        self.assertEqual(applied, 14)
        self.assertEqual(len(connection.records[14]["checksum"]), 64)

    def test_statement_splitter_preserves_semicolons_in_strings(self) -> None:
        statements = split_sql_statements(
            "INSERT INTO notes VALUES ('first;second'); SELECT 1;"
        )

        self.assertEqual(
            statements,
            ("INSERT INTO notes VALUES ('first;second')", "SELECT 1"),
        )

    def test_statement_splitter_rejects_unterminated_quote(self) -> None:
        with self.assertRaisesRegex(ValueError, "unterminated"):
            split_sql_statements("SELECT 'broken;")


if __name__ == "__main__":
    unittest.main()
