import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parents[1] / "src"))

from fundos.storage.database import SCHEMA  # noqa: E402
from fundos.storage.postgres_migrations import (  # noqa: E402
    POSTGRES_BASELINE_VERSION,
    apply_postgres_migrations,
    postgres_migrations,
    split_sql_statements,
    sqlite_schema_to_postgres,
)


class Result:
    def __init__(self, rows=()):
        self.rows = rows

    def fetchall(self):
        return self.rows


class MigrationConnection:
    def __init__(self):
        self.versions = set()
        self.calls = []

    def execute(self, query, parameters=()):
        self.calls.append((query, parameters))
        normalized = " ".join(query.split()).lower()
        if normalized.startswith("select version from schema_migrations"):
            return Result([{"version": version} for version in sorted(self.versions)])
        if normalized.startswith("insert into schema_migrations"):
            self.versions.add(parameters[0])
        return Result()


class PostgresMigrationTests(unittest.TestCase):
    def test_converts_current_schema_to_postgres_ddl(self) -> None:
        converted = sqlite_schema_to_postgres(SCHEMA)

        self.assertNotIn("PRAGMA", converted)
        self.assertNotIn("AUTOINCREMENT", converted)
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", converted)
        self.assertIn("CREATE TABLE IF NOT EXISTS benchmark_nav", converted)

    def test_builds_version_14_baseline_with_individual_statements(self) -> None:
        migrations = postgres_migrations(SCHEMA)

        self.assertEqual(len(migrations), 1)
        self.assertEqual(migrations[0].version, POSTGRES_BASELINE_VERSION)
        self.assertGreater(len(migrations[0].statements), 30)
        self.assertTrue(all(";" not in statement for statement in migrations[0].statements))

    def test_applies_baseline_idempotently(self) -> None:
        connection = MigrationConnection()

        first = apply_postgres_migrations(connection, SCHEMA)
        calls_after_first = len(connection.calls)
        second = apply_postgres_migrations(connection, SCHEMA)

        self.assertEqual(first, POSTGRES_BASELINE_VERSION)
        self.assertEqual(second, POSTGRES_BASELINE_VERSION)
        self.assertEqual(connection.versions, {POSTGRES_BASELINE_VERSION})
        second_run_calls = connection.calls[calls_after_first:]
        self.assertEqual(len(second_run_calls), 2)

    def test_statement_splitter_preserves_semicolons_in_strings(self) -> None:
        statements = split_sql_statements(
            "INSERT INTO notes VALUES ('first;second'); SELECT 1;"
        )

        self.assertEqual(
            statements,
            ("INSERT INTO notes VALUES ('first;second')", "SELECT 1"),
        )

    def test_statement_splitter_rejects_unterminated_quote(self) -> None:
        with self.assertRaisesRegex(ValueError, "unterminated"):
            split_sql_statements("SELECT 'broken;")


if __name__ == "__main__":
    unittest.main()
