from dataclasses import dataclass
from hashlib import sha256
import re
from typing import Any

from fundos.storage.versions import CURRENT_SCHEMA_VERSION


POSTGRES_BASELINE_VERSION = 14
EVIDENCE_INDEX_SQL = """
CREATE INDEX IF NOT EXISTS idx_raw_evidence_review_published
ON raw_research_evidence (review_status, published_at);
""".strip()


@dataclass(frozen=True, slots=True)
class PostgresMigration:
    version: int
    name: str
    statements: tuple[str, ...]
    rollback_statements: tuple[str, ...] = ()

    @property
    def checksum(self) -> str:
        payload = "\n-- up\n".join(self.statements)
        payload += "\n-- down\n" + "\n".join(self.rollback_statements)
        return sha256(
            f"{self.version}\n{self.name}\n{payload}".encode("utf-8")
        ).hexdigest()

    @property
    def reversible(self) -> bool:
        return bool(self.rollback_statements)


def split_sql_statements(script: str) -> tuple[str, ...]:
    statements: list[str] = []
    current: list[str] = []
    quote: str | None = None
    index = 0
    while index < len(script):
        character = script[index]
        if quote is not None:
            current.append(character)
            if character == quote:
                if index + 1 < len(script) and script[index + 1] == quote:
                    current.append(script[index + 1])
                    index += 1
                else:
                    quote = None
        elif character in ("'", '"'):
            quote = character
            current.append(character)
        elif character == ";":
            statement = "".join(current).strip()
            if statement:
                statements.append(statement)
            current = []
        else:
            current.append(character)
        index += 1
    if quote is not None:
        raise ValueError("SQL script contains an unterminated quoted string")
    trailing = "".join(current).strip()
    if trailing:
        statements.append(trailing)
    return tuple(statements)


def sqlite_schema_to_postgres(sqlite_schema: str) -> str:
    lines = [
        line
        for line in sqlite_schema.splitlines()
        if not line.strip().upper().startswith("PRAGMA ")
    ]
    converted = "\n".join(lines).replace(EVIDENCE_INDEX_SQL, "")
    converted = converted.replace(
        "INTEGER PRIMARY KEY AUTOINCREMENT",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    )
    return re.sub(r"\bREAL\b", "DOUBLE PRECISION", converted)


def postgres_migrations(sqlite_schema: str) -> tuple[PostgresMigration, ...]:
    baseline = sqlite_schema_to_postgres(sqlite_schema)
    return (
        PostgresMigration(
            POSTGRES_BASELINE_VERSION,
            "baseline_current_schema",
            split_sql_statements(baseline),
        ),
        PostgresMigration(
            15,
            "index_raw_evidence_review_queue",
            (EVIDENCE_INDEX_SQL.removesuffix(";"),),
            ("DROP INDEX IF EXISTS idx_raw_evidence_review_published",),
        ),
    )


def apply_postgres_migrations(
    connection: Any,
    sqlite_schema: str,
    *,
    target_version: int = CURRENT_SCHEMA_VERSION,
) -> int:
    migrations = postgres_migrations(sqlite_schema)
    migration_by_version = {migration.version: migration for migration in migrations}
    if target_version < POSTGRES_BASELINE_VERSION or target_version > CURRENT_SCHEMA_VERSION:
        raise ValueError(
            f"PostgreSQL target version must be between "
            f"{POSTGRES_BASELINE_VERSION} and {CURRENT_SCHEMA_VERSION}"
        )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS schema_migrations (
            version INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            checksum TEXT,
            applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    connection.execute(
        "ALTER TABLE schema_migrations ADD COLUMN IF NOT EXISTS checksum TEXT"
    )
    rows = connection.execute(
        "SELECT version, name, checksum FROM schema_migrations ORDER BY version"
    ).fetchall()
    applied = {
        int(_value(row, "version", 0)): {
            "name": str(_value(row, "name", 1)),
            "checksum": _value(row, "checksum", 2),
        }
        for row in rows
    }
    unknown = set(applied) - set(migration_by_version)
    if unknown:
        raise ValueError(f"unknown PostgreSQL migration versions: {sorted(unknown)}")
    for version, record in applied.items():
        migration = migration_by_version[version]
        if record["name"] != migration.name:
            raise ValueError(f"PostgreSQL migration {version} name mismatch")
        if record["checksum"] is None:
            connection.execute(
                "UPDATE schema_migrations SET checksum = ? WHERE version = ?",
                (migration.checksum, version),
            )
        elif record["checksum"] != migration.checksum:
            raise ValueError(f"PostgreSQL migration {version} checksum mismatch")

    for version in sorted(applied, reverse=True):
        if version <= target_version:
            continue
        migration = migration_by_version[version]
        if not migration.reversible:
            raise ValueError(f"PostgreSQL migration {version} is not reversible")
        for statement in migration.rollback_statements:
            connection.execute(statement)
        connection.execute(
            "DELETE FROM schema_migrations WHERE version = ?",
            (version,),
        )
        del applied[version]

    for migration in migrations:
        if migration.version > target_version or migration.version in applied:
            continue
        for statement in migration.statements:
            connection.execute(statement)
        connection.execute(
            """
            INSERT INTO schema_migrations (version, name, checksum)
            VALUES (?, ?, ?)
            """,
            (migration.version, migration.name, migration.checksum),
        )
        applied[migration.version] = {
            "name": migration.name,
            "checksum": migration.checksum,
        }
    return max(applied, default=0)


def _value(row: Any, key: str, index: int) -> Any:
    return row[key] if isinstance(row, dict) else row[index]
