from dataclasses import dataclass
from typing import Any


POSTGRES_BASELINE_VERSION = 14


@dataclass(frozen=True, slots=True)
class PostgresMigration:
    version: int
    name: str
    statements: tuple[str, ...]


def split_sql_statements(script: str) -> tuple[str, ...]:
    statements: list[str] = []
    current: list[str] = []
    quote: str | None = None
    index = 0
    while index < len(script):
        character = script[index]
        if quote is not None:
            current.append(character)
            if character == quote:
                if index + 1 < len(script) and script[index + 1] == quote:
                    current.append(script[index + 1])
                    index += 1
                else:
                    quote = None
        elif character in ("'", '"'):
            quote = character
            current.append(character)
        elif character == ";":
            statement = "".join(current).strip()
            if statement:
                statements.append(statement)
            current = []
        else:
            current.append(character)
        index += 1
    if quote is not None:
        raise ValueError("SQL script contains an unterminated quoted string")
    trailing = "".join(current).strip()
    if trailing:
        statements.append(trailing)
    return tuple(statements)


def sqlite_schema_to_postgres(sqlite_schema: str) -> str:
    lines = [
        line
        for line in sqlite_schema.splitlines()
        if not line.strip().upper().startswith("PRAGMA ")
    ]
    return "\n".join(lines).replace(
        "INTEGER PRIMARY KEY AUTOINCREMENT",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    )


def postgres_migrations(sqlite_schema: str) -> tuple[PostgresMigration, ...]:
    baseline = sqlite_schema_to_postgres(sqlite_schema)
    return (
        PostgresMigration(
            POSTGRES_BASELINE_VERSION,
            "baseline_current_schema",
            split_sql_statements(baseline),
        ),
    )


def apply_postgres_migrations(connection: Any, sqlite_schema: str) -> int:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS schema_migrations (
            version INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    rows = connection.execute(
        "SELECT version FROM schema_migrations ORDER BY version"
    ).fetchall()
    applied = {
        int(row["version"] if isinstance(row, dict) else row[0])
        for row in rows
    }
    for migration in postgres_migrations(sqlite_schema):
        if migration.version in applied:
            continue
        for statement in migration.statements:
            connection.execute(statement)
        connection.execute(
            """
            INSERT INTO schema_migrations (version, name)
            VALUES (?, ?)
            """,
            (migration.version, migration.name),
        )
        applied.add(migration.version)
    return max(applied, default=0)
